# Generated by actant-sdk-codegen. Edit the template, not this file.
import json
import urllib.parse
import urllib.request

_ALLOWED_URL_SCHEMES = {"http", "https"}


def _validate_url_scheme(url):
    scheme = urllib.parse.urlparse(url).scheme
    if scheme not in _ALLOWED_URL_SCHEMES:
        allowed = ", ".join(sorted(_ALLOWED_URL_SCHEMES))
        raise ValueError(f"ActantClient only supports these URL schemes: {allowed}")


def _build_http_opener():
    opener = urllib.request.OpenerDirector()
    opener.add_handler(urllib.request.HTTPHandler())
    opener.add_handler(urllib.request.HTTPSHandler())
    opener.add_handler(urllib.request.HTTPDefaultErrorHandler())
    opener.add_handler(urllib.request.HTTPRedirectHandler())
    opener.add_handler(urllib.request.HTTPErrorProcessor())
    return opener


_HTTP_OPENER = _build_http_opener()


def _open_http_request(req):
    _validate_url_scheme(req.full_url)
    return _HTTP_OPENER.open(req)


class ActantClient:
    def __init__(self, base="http://127.0.0.1:4555"):
        _validate_url_scheme(base)
        self.base = base

    def command(self, workspace_id, actor_id, command_type, input_, idempotency_key=None):
        body = {
            "workspace_id": workspace_id,
            "actor_id": actor_id,
            "command_type": command_type,
            "input": input_,
        }
        if idempotency_key:
            body["idempotency_key"] = idempotency_key
        req = urllib.request.Request(
            self.base + "/v1/command",
            data=json.dumps(body).encode("utf-8"),
            headers={"content-type": "application/json"},
        )
        with _open_http_request(req) as r:
            return json.loads(r.read())
