// Generated by actant-sdk-codegen. Edit the template, not this file.
import Foundation

public struct ActantClient {
    public let base: URL

    public init(base: URL = URL(string: "http://127.0.0.1:4555")!) {
        self.base = base
    }

    public func command(workspace: String, actor: String, type: String, input: [String: Any]) async throws -> Data {
        var req = URLRequest(url: base.appendingPathComponent("v1/command"))
        req.httpMethod = "POST"
        req.setValue("application/json", forHTTPHeaderField: "content-type")
        let body: [String: Any] = [
            "workspace_id": workspace,
            "actor_id": actor,
            "command_type": type,
            "input": input,
        ]
        req.httpBody = try JSONSerialization.data(withJSONObject: body)
        let (data, _) = try await URLSession.shared.data(for: req)
        return data
    }
}
