# Generated by actant-sdk-codegen. Edit the template, not this file.
import urllib.request, json

class ActantClient:
    def __init__(self, base="http://127.0.0.1:4555"):
        self.base = base

    def command(self, workspace_id, actor_id, command_type, input_, idempotency_key=None):
        body = {
            "workspace_id": workspace_id,
            "actor_id": actor_id,
            "command_type": command_type,
            "input": input_,
        }
        if idempotency_key:
            body["idempotency_key"] = idempotency_key
        req = urllib.request.Request(
            self.base + "/v1/command",
            data=json.dumps(body).encode("utf-8"),
            headers={"content-type": "application/json"},
        )
        with urllib.request.urlopen(req) as r:
            return json.loads(r.read())
