// Generated by actant-sdk-codegen. Edit the template, not this file.
export class ActantClient {
  constructor(private base = "http://127.0.0.1:4555") {}
  async command(input: { workspace_id: string; actor_id: string; command_type: string; input: unknown; idempotency_key?: string }) {
    const r = await fetch(this.base + "/v1/command", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(input),
    });
    if (!r.ok) throw new Error("HTTP " + r.status);
    return r.json();
  }
}
