// Generated by uniffi-bindgen. Do not edit by hand.

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(actant_ffiFFI)
import actant_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_actant_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_actant_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * Opaque, reference-counted ActantDB handle exposed to Swift / Kotlin.
 *
 * Wraps the SQLite-backed [`Storage`] + the command [`Engine`] + the
 * caller-supplied workspace / actor identity so every `dispatch()` call
 * over the FFI boundary doesn't have to re-thread those args.
 *
 * The struct itself is not `Clone`; uniffi hands out `Arc<Self>` to the
 * host language and keeps lifetime correct without explicit close calls
 * (though [`Self::close`] is exposed for consumers that want to release
 * the underlying connection pool eagerly).
 */
public protocol ActantHandleProtocol : AnyObject {

    /**
     * Release the underlying connection pool eagerly.
     *
     * uniffi will also drop the handle when the host releases its last
     * reference; calling `close()` is only necessary when the consumer
     * wants the SQLite file unlocked before the wrapper falls out of
     * scope (e.g. before deleting it from disk).
     */
    func close() async

    /**
     * Dispatch a command. `input_json` must parse as a JSON object.
     *
     * Mirrors [`actant_command::Engine::dispatch`] one-to-one; the only
     * shape change is `result` being re-encoded as a JSON string so the
     * FFI ABI stays flat.
     */
    func dispatch(commandType: String, inputJson: String, idempotencyKey: String?) async throws  -> CommandOutcome

    /**
     * Read events for the bound workspace newer than the supplied HLC
     * cursor, oldest first.

     */
    func eventsSince(cursorHlcPhysicalMs: UInt64?, cursorHlcLogical: UInt32?, limit: UInt32) async throws  -> [EventRow]

    /**
     * Batch-ingest events from a peer.
     */
    func ingest(events: [EventRow]) async throws  -> IngestReport

}

/**
 * Opaque, reference-counted ActantDB handle exposed to Swift / Kotlin.
 *
 * Wraps the SQLite-backed [`Storage`] + the command [`Engine`] + the
 * caller-supplied workspace / actor identity so every `dispatch()` call
 * over the FFI boundary doesn't have to re-thread those args.
 *
 * The struct itself is not `Clone`; uniffi hands out `Arc<Self>` to the
 * host language and keeps lifetime correct without explicit close calls
 * (though [`Self::close`] is exposed for consumers that want to release
 * the underlying connection pool eagerly).
 */
open class ActantHandle:
    ActantHandleProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_actant_ffi_fn_clone_actanthandle(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_actant_ffi_fn_free_actanthandle(pointer, $0) }
    }


    /**
     * Open (or create) an ActantDB at `store_dir`, applying every bundled
     * migration, and bind the handle to `workspace_id` + `actor_id`.
     *
     * `store_dir` is treated as a directory; the SQLite file lives at
     * `<store_dir>/actantdb.sqlite`. iOS callers should pass the
     * app-sandbox Application Support directory.
     */
public static func `open`(storeDir: String, workspaceId: String, actorId: String)async throws  -> ActantHandle {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_actant_ffi_fn_constructor_actanthandle_open(FfiConverterString.lower(storeDir),FfiConverterString.lower(workspaceId),FfiConverterString.lower(actorId)
                )
            },
            pollFunc: ffi_actant_ffi_rust_future_poll_pointer,
            completeFunc: ffi_actant_ffi_rust_future_complete_pointer,
            freeFunc: ffi_actant_ffi_rust_future_free_pointer,
            liftFunc: FfiConverterTypeActantHandle.lift,
            errorHandler: FfiConverterTypeFfiError.lift
        )
}



    /**
     * Release the underlying connection pool eagerly.
     *
     * uniffi will also drop the handle when the host releases its last
     * reference; calling `close()` is only necessary when the consumer
     * wants the SQLite file unlocked before the wrapper falls out of
     * scope (e.g. before deleting it from disk).
     */
open func close()async  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_actant_ffi_fn_method_actanthandle_close(
                    self.uniffiClonePointer()

                )
            },
            pollFunc: ffi_actant_ffi_rust_future_poll_void,
            completeFunc: ffi_actant_ffi_rust_future_complete_void,
            freeFunc: ffi_actant_ffi_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: nil

        )
}

    /**
     * Dispatch a command. `input_json` must parse as a JSON object.
     *
     * Mirrors [`actant_command::Engine::dispatch`] one-to-one; the only
     * shape change is `result` being re-encoded as a JSON string so the
     * FFI ABI stays flat.
     */
open func dispatch(commandType: String, inputJson: String, idempotencyKey: String?)async throws  -> CommandOutcome {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_actant_ffi_fn_method_actanthandle_dispatch(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(commandType),FfiConverterString.lower(inputJson),FfiConverterOptionString.lower(idempotencyKey)
                )
            },
            pollFunc: ffi_actant_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_actant_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_actant_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeCommandOutcome.lift,
            errorHandler: FfiConverterTypeFfiError.lift
        )
}

    /**
     * Read events for the bound workspace newer than the supplied HLC
     * cursor, oldest first.

     */
open func eventsSince(cursorHlcPhysicalMs: UInt64?, cursorHlcLogical: UInt32?, limit: UInt32)async throws  -> [EventRow] {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_actant_ffi_fn_method_actanthandle_events_since(
                    self.uniffiClonePointer(),
                    FfiConverterOptionUInt64.lower(cursorHlcPhysicalMs),FfiConverterOptionUInt32.lower(cursorHlcLogical),FfiConverterUInt32.lower(limit)
                )
            },
            pollFunc: ffi_actant_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_actant_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_actant_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeEventRow.lift,
            errorHandler: FfiConverterTypeFfiError.lift
        )
}

    /**
     * Batch-ingest events from a peer.
     */
open func ingest(events: [EventRow])async throws  -> IngestReport {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_actant_ffi_fn_method_actanthandle_ingest(
                    self.uniffiClonePointer(),
                    FfiConverterSequenceTypeEventRow.lower(events)
                )
            },
            pollFunc: ffi_actant_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_actant_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_actant_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeIngestReport.lift,
            errorHandler: FfiConverterTypeFfiError.lift
        )
}


}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeActantHandle: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = ActantHandle

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> ActantHandle {
        return ActantHandle(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: ActantHandle) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ActantHandle {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: ActantHandle, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeActantHandle_lift(_ pointer: UnsafeMutableRawPointer) throws -> ActantHandle {
    return try FfiConverterTypeActantHandle.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeActantHandle_lower(_ value: ActantHandle) -> UnsafeMutableRawPointer {
    return FfiConverterTypeActantHandle.lower(value)
}


/**
 * Result of dispatching a command across the FFI boundary.
 *
 * `result_json` is the canonical JSON form of
 * [`actant_command::CommandOutcome::result`] so the consumer can decode it
 * in whatever Swift / Kotlin type they want without us baking a schema in
 * here.
 */
public struct CommandOutcome {
    /**
     * Command record id assigned by the engine.
     */
    public var commandId: String
    /**
     * Chronicle event id, when the command produced one (most do; idempotent
     * replays do not).
     */
    public var eventId: String?
    /**
     * Canonical JSON-encoded `serde_json::Value` returned by the engine.
     */
    public var resultJson: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Command record id assigned by the engine.
         */commandId: String,
        /**
         * Chronicle event id, when the command produced one (most do; idempotent
         * replays do not).
         */eventId: String?,
        /**
         * Canonical JSON-encoded `serde_json::Value` returned by the engine.
         */resultJson: String) {
        self.commandId = commandId
        self.eventId = eventId
        self.resultJson = resultJson
    }
}



extension CommandOutcome: Equatable, Hashable {
    public static func ==(lhs: CommandOutcome, rhs: CommandOutcome) -> Bool {
        if lhs.commandId != rhs.commandId {
            return false
        }
        if lhs.eventId != rhs.eventId {
            return false
        }
        if lhs.resultJson != rhs.resultJson {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(commandId)
        hasher.combine(eventId)
        hasher.combine(resultJson)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCommandOutcome: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CommandOutcome {
        return
            try CommandOutcome(
                commandId: FfiConverterString.read(from: &buf),
                eventId: FfiConverterOptionString.read(from: &buf),
                resultJson: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: CommandOutcome, into buf: inout [UInt8]) {
        FfiConverterString.write(value.commandId, into: &buf)
        FfiConverterOptionString.write(value.eventId, into: &buf)
        FfiConverterString.write(value.resultJson, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCommandOutcome_lift(_ buf: RustBuffer) throws -> CommandOutcome {
    return try FfiConverterTypeCommandOutcome.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCommandOutcome_lower(_ value: CommandOutcome) -> RustBuffer {
    return FfiConverterTypeCommandOutcome.lower(value)
}


/**
 * One row from the Chronicle, hoisted to a flat FFI-safe shape.

 */
public struct EventRow {
    /**
     * Stable event id (today: ULID; post-#42: HLC + sha256 content hash).
     */
    public var id: String
    /**
     * Session id this event belongs to, when applicable.
     */
    public var sessionId: String?
    /**
     * Free-form event type discriminator (`session_created`, `tool_call_*`, …).
     */
    public var eventType: String
    /**
     * Canonical JSON payload (whatever was in `payload_inline`).
     */
    public var payloadJson: String
    /**
     * SHA-256 of `payload_json`.
     */
    public var payloadHash: String
    /**
     * RFC-3339 wall-clock stamp recorded at append time.
     */
    public var createdAt: String
    /**
     * Originating device.
     */
    public var deviceId: String
    /**
     * HLC physical component (ms).
     */
    public var hlcPhysicalMs: UInt64
    /**
     * HLC logical component.
     */
    public var hlcLogical: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Stable event id (today: ULID; post-#42: HLC + sha256 content hash).
         */id: String,
        /**
         * Session id this event belongs to, when applicable.
         */sessionId: String?,
        /**
         * Free-form event type discriminator (`session_created`, `tool_call_*`, …).
         */eventType: String,
        /**
         * Canonical JSON payload (whatever was in `payload_inline`).
         */payloadJson: String,
        /**
         * SHA-256 of `payload_json`.
         */payloadHash: String,
        /**
         * RFC-3339 wall-clock stamp recorded at append time.
         */createdAt: String,
        /**
         * Originating device.
         */deviceId: String,
        /**
         * HLC physical component (ms).
         */hlcPhysicalMs: UInt64,
        /**
         * HLC logical component.
         */hlcLogical: UInt32) {
        self.id = id
        self.sessionId = sessionId
        self.eventType = eventType
        self.payloadJson = payloadJson
        self.payloadHash = payloadHash
        self.createdAt = createdAt
        self.deviceId = deviceId
        self.hlcPhysicalMs = hlcPhysicalMs
        self.hlcLogical = hlcLogical
    }
}



extension EventRow: Equatable, Hashable {
    public static func ==(lhs: EventRow, rhs: EventRow) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.sessionId != rhs.sessionId {
            return false
        }
        if lhs.eventType != rhs.eventType {
            return false
        }
        if lhs.payloadJson != rhs.payloadJson {
            return false
        }
        if lhs.payloadHash != rhs.payloadHash {
            return false
        }
        if lhs.createdAt != rhs.createdAt {
            return false
        }
        if lhs.deviceId != rhs.deviceId {
            return false
        }
        if lhs.hlcPhysicalMs != rhs.hlcPhysicalMs {
            return false
        }
        if lhs.hlcLogical != rhs.hlcLogical {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(sessionId)
        hasher.combine(eventType)
        hasher.combine(payloadJson)
        hasher.combine(payloadHash)
        hasher.combine(createdAt)
        hasher.combine(deviceId)
        hasher.combine(hlcPhysicalMs)
        hasher.combine(hlcLogical)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEventRow: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EventRow {
        return
            try EventRow(
                id: FfiConverterString.read(from: &buf),
                sessionId: FfiConverterOptionString.read(from: &buf),
                eventType: FfiConverterString.read(from: &buf),
                payloadJson: FfiConverterString.read(from: &buf),
                payloadHash: FfiConverterString.read(from: &buf),
                createdAt: FfiConverterString.read(from: &buf),
                deviceId: FfiConverterString.read(from: &buf),
                hlcPhysicalMs: FfiConverterUInt64.read(from: &buf),
                hlcLogical: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: EventRow, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterOptionString.write(value.sessionId, into: &buf)
        FfiConverterString.write(value.eventType, into: &buf)
        FfiConverterString.write(value.payloadJson, into: &buf)
        FfiConverterString.write(value.payloadHash, into: &buf)
        FfiConverterString.write(value.createdAt, into: &buf)
        FfiConverterString.write(value.deviceId, into: &buf)
        FfiConverterUInt64.write(value.hlcPhysicalMs, into: &buf)
        FfiConverterUInt32.write(value.hlcLogical, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEventRow_lift(_ buf: RustBuffer) throws -> EventRow {
    return try FfiConverterTypeEventRow.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEventRow_lower(_ value: EventRow) -> RustBuffer {
    return FfiConverterTypeEventRow.lower(value)
}


/**
 * Outcome of a batch ingest.
 */
public struct IngestReport {
    /**
     * Events newly written.
     */
    public var accepted: UInt32
    /**
     * Events that were already present (id collision; idempotent skip).
     */
    public var skipped: UInt32
    /**
     * Per-event rejection reasons. Empty when everything was either
     * accepted or skipped.
     */
    public var rejected: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Events newly written.
         */accepted: UInt32,
        /**
         * Events that were already present (id collision; idempotent skip).
         */skipped: UInt32,
        /**
         * Per-event rejection reasons. Empty when everything was either
         * accepted or skipped.
         */rejected: [String]) {
        self.accepted = accepted
        self.skipped = skipped
        self.rejected = rejected
    }
}



extension IngestReport: Equatable, Hashable {
    public static func ==(lhs: IngestReport, rhs: IngestReport) -> Bool {
        if lhs.accepted != rhs.accepted {
            return false
        }
        if lhs.skipped != rhs.skipped {
            return false
        }
        if lhs.rejected != rhs.rejected {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(accepted)
        hasher.combine(skipped)
        hasher.combine(rejected)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeIngestReport: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> IngestReport {
        return
            try IngestReport(
                accepted: FfiConverterUInt32.read(from: &buf),
                skipped: FfiConverterUInt32.read(from: &buf),
                rejected: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: IngestReport, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.accepted, into: &buf)
        FfiConverterUInt32.write(value.skipped, into: &buf)
        FfiConverterSequenceString.write(value.rejected, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIngestReport_lift(_ buf: RustBuffer) throws -> IngestReport {
    return try FfiConverterTypeIngestReport.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIngestReport_lower(_ value: IngestReport) -> RustBuffer {
    return FfiConverterTypeIngestReport.lower(value)
}


/**
 * FFI-safe flattening of [`ActantError`].
 *
 * Several `ActantError` variants collapse into the same FFI variant on
 * purpose — Swift / Kotlin consumers don't need every internal distinction
 * the Rust side draws. The mapping table:
 *
 * | `ActantError`           | `FfiError`           |
 * |-------------------------|----------------------|
 * | `Storage`               | `Storage`            |
 * | `Internal`              | `Storage`            |
 * | `NotImplemented`        | `Storage`            |
 * | `NotFound`              | `NotFound`           |
 * | `InvalidInput`          | `InvalidInput`       |
 * | `Conflict`              | `InvalidInput`       |
 * | `PermissionDenied`      | `PermissionDenied`   |
 * | `PolicyHalt`            | `PermissionDenied`   |
 * | `ApprovalDenied`        | `PermissionDenied`   |
 * | `ApprovalRequired`      | `ApprovalRequired`   |
 * | `IdempotentReplay`      | `IdempotentReplay`   |
 *
 * `RateLimited` has no current source in `ActantError`; it's reserved for
 * future throttle-driven failures wired through [`actant-reliability`].
 */
public enum FfiError {



    /**
     * Underlying storage / I/O failure.
     */
    case Storage(message: String)

    /**
     * The named resource doesn't exist.
     */
    case NotFound(message: String)

    /**
     * Caller-supplied input failed validation or a conflict check.
     */
    case InvalidInput(message: String)

    /**
     * Policy refused the action outright.
     */
    case PermissionDenied(message: String)

    /**
     * Policy requires a human approval before the action can proceed.
     */
    case ApprovalRequired(message: String)

    /**
     * Caller is being throttled (reserved; not produced today).
     */
    case RateLimited(message: String)

    /**
     * Idempotency key matched a prior command — see the prior outcome.
     */
    case IdempotentReplay(message: String)

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiError: FfiConverterRustBuffer {
    typealias SwiftType = FfiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {




        case 1: return .Storage(
            message: try FfiConverterString.read(from: &buf)
        )

        case 2: return .NotFound(
            message: try FfiConverterString.read(from: &buf)
        )

        case 3: return .InvalidInput(
            message: try FfiConverterString.read(from: &buf)
        )

        case 4: return .PermissionDenied(
            message: try FfiConverterString.read(from: &buf)
        )

        case 5: return .ApprovalRequired(
            message: try FfiConverterString.read(from: &buf)
        )

        case 6: return .RateLimited(
            message: try FfiConverterString.read(from: &buf)
        )

        case 7: return .IdempotentReplay(
            message: try FfiConverterString.read(from: &buf)
        )


        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiError, into buf: inout [UInt8]) {
        switch value {




        case .Storage(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .NotFound(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .InvalidInput(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .PermissionDenied(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))
        case .ApprovalRequired(_ /* message is ignored*/):
            writeInt(&buf, Int32(5))
        case .RateLimited(_ /* message is ignored*/):
            writeInt(&buf, Int32(6))
        case .IdempotentReplay(_ /* message is ignored*/):
            writeInt(&buf, Int32(7))


        }
    }
}


extension FfiError: Equatable, Hashable {}

extension FfiError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt32: FfiConverterRustBuffer {
    typealias SwiftType = UInt32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeEventRow: FfiConverterRustBuffer {
    typealias SwiftType = [EventRow]

    public static func write(_ value: [EventRow], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeEventRow.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [EventRow] {
        let len: Int32 = try readInt(&buf)
        var seq = [EventRow]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeEventRow.read(from: &buf))
        }
        return seq
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_MAYBE_READY: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call uniffiEnsureInitialized() since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                uniffiFutureContinuationCallback,
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_actant_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_actant_ffi_checksum_method_actanthandle_close() != 39564) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_actant_ffi_checksum_method_actanthandle_dispatch() != 34582) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_actant_ffi_checksum_method_actanthandle_events_since() != 61773) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_actant_ffi_checksum_method_actanthandle_ingest() != 24034) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_actant_ffi_checksum_constructor_actanthandle_open() != 51348) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all