# Generated by actant-sdk-codegen. Edit the template, not this file.
import json
import urllib.parse
import urllib.request

_ALLOWED_URL_SCHEMES = {"http", "https"}


def _validate_url_scheme(url):
    scheme = urllib.parse.urlparse(url).scheme
    if scheme not in _ALLOWED_URL_SCHEMES:
        allowed = ", ".join(sorted(_ALLOWED_URL_SCHEMES))
        raise ValueError(f"ActantClient only supports these URL schemes: {allowed}")


def _build_http_opener():
    opener = urllib.request.OpenerDirector()
    opener.add_handler(urllib.request.HTTPHandler())
    opener.add_handler(urllib.request.HTTPSHandler())
    opener.add_handler(urllib.request.HTTPDefaultErrorHandler())
    opener.add_handler(urllib.request.HTTPRedirectHandler())
    opener.add_handler(urllib.request.HTTPErrorProcessor())
    return opener


_HTTP_OPENER = _build_http_opener()


def _open_http_request(req, timeout):
    _validate_url_scheme(req.full_url)
    return _HTTP_OPENER.open(req, timeout=timeout)


class ActantClient:
    def __init__(self, base="http://127.0.0.1:4555", timeout_seconds=30):
        _validate_url_scheme(base)
        self.base = base
        self.timeout_seconds = timeout_seconds

    def command(
        self,
        workspace_id,
        actor_id,
        command_type,
        input_,
        idempotency_key=None,
        timeout_seconds=None,
    ):
        body = {
            "workspace_id": workspace_id,
            "actor_id": actor_id,
            "command_type": command_type,
            "input": input_,
        }
        if idempotency_key:
            body["idempotency_key"] = idempotency_key
        req = urllib.request.Request(
            urllib.parse.urljoin(self.base.rstrip("/") + "/", "v1/command"),
            data=json.dumps(body).encode("utf-8"),
            headers={"content-type": "application/json"},
        )
        timeout = self.timeout_seconds if timeout_seconds is None else timeout_seconds
        with _open_http_request(req, timeout) as r:
            body = r.read()
            try:
                return json.loads(body)
            except json.JSONDecodeError as e:
                snippet = body[:200].decode("utf-8", "replace")
                raise ValueError(f"Invalid JSON response from server: {e}; body={snippet!r}") from e
