// Generated by actant-sdk-codegen. Edit the template, not this file.
export class ActantClient {
  constructor(private base = "http://127.0.0.1:4555") {
    const url = new URL(base);
    if (url.protocol !== "http:" && url.protocol !== "https:") {
      throw new Error("ActantClient only supports http and https schemes");
    }
    this.base = url.toString();
  }
  async command(input: { workspace_id: string; actor_id: string; command_type: string; input: unknown; idempotency_key?: string }) {
    const r = await fetch(new URL("/v1/command", this.base).toString(), {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(input),
    });
    const body = await r.text();
    if (!r.ok) throw new Error("HTTP " + r.status + ": request failed");
    try {
      return JSON.parse(body);
    } catch (e) {
      const message = e instanceof Error ? e.message : String(e);
      throw new Error("HTTP " + r.status + " returned invalid JSON: " + message);
    }
  }
}
