// Generated by actant-sdk-codegen. Edit the template, not this file.
import Foundation

public enum ActantClientError: Error, Equatable {
    case invalidScheme(String?)
}

public struct ActantClient {
    private static let defaultBase = URL(string: "http://127.0.0.1:4555")!

    public let base: URL

    public init(base: URL) throws {
        guard base.scheme == "http" || base.scheme == "https" else {
            throw ActantClientError.invalidScheme(base.scheme)
        }
        self.base = base
    }

    public init() {
        self.base = Self.defaultBase
    }

    public func command(
        workspace: String,
        actor: String,
        type: String,
        input: [String: Any],
        idempotencyKey: String? = nil
    ) async throws -> Data {
        var req = URLRequest(url: base.appendingPathComponent("v1/command"))
        req.httpMethod = "POST"
        req.setValue("application/json", forHTTPHeaderField: "content-type")
        var body: [String: Any] = [
            "workspace_id": workspace,
            "actor_id": actor,
            "command_type": type,
            "input": input,
        ]
        if let idempotencyKey {
            body["idempotency_key"] = idempotencyKey
        }
        req.httpBody = try JSONSerialization.data(withJSONObject: body)
        let (data, response) = try await URLSession.shared.data(for: req)
        guard let http = response as? HTTPURLResponse, (200...299).contains(http.statusCode) else {
            throw URLError(.badServerResponse)
        }
        return data
    }
}
