{{- if and (eq .Values.storage.backend "sqlite") .Values.storage.sqlite.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "actantdb.fullname" . }}-data
  labels:
    {{- include "actantdb.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.sqlite.persistence.size }}
{{- end }}
