//! actant-templates — single-project scaffolding template.

#![forbid(unsafe_code)]
#![warn(missing_docs)]

pub mod registry;
pub mod render;

pub use registry::{
    RenderOutput, RenderRequest, Template, TemplateError, TemplateRegistry, DEFAULT_PORT,
    DEFAULT_STUDIO_PORT,
};
pub use render::substitute;

/// Returns a minimal package.json content.
pub fn package_json(name: &str) -> String {
    serde_json::json!({
        "name": name,
        "version": "0.0.1",
        "private": true,
        "type": "module",
        "scripts": { "demo": "node ./demo.mjs" }
    })
    .to_string()
}

/// Returns a minimal README body.
pub fn readme(name: &str) -> String {
    format!(
        "# {name}\n\nGenerated by `actantdb init`. Run the server:\n\n```\nactantdb serve --db ./actant.db\n```\n"
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn renders_package_json() {
        let p = package_json("hello");
        assert!(p.contains("\"hello\""));
    }
}

/// Write a minimal project under `root`. Closes the
/// `actant-codegen-project` consolidation — that crate was a 30-line
/// wrapper around `package_json` + `readme` above; collapsed into this
/// crate to drop one workspace member.
pub fn scaffold(root: &std::path::Path, name: &str) -> std::io::Result<()> {
    std::fs::create_dir_all(root)?;
    std::fs::write(root.join("package.json"), package_json(name))?;
    std::fs::write(root.join("README.md"), readme(name))?;
    Ok(())
}
